### ISSUE TITLE
After Market creation back button in market details view is routing you back to create market process

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1014]
The back button should route back to the main market overview page which is default on https://omen.eth.link/

**Comment by pimato** [comment]
It seems like there is in general an issue with the back button.
If you go directly to https://omen.eth.link/#/0xffbc624070cb014420a6f7547fd05dfe635e2db2 it will not allow to get you back to the main view.

**Comment by KadenZipfel** [comment]
This is my bad. I recall changing the back buttons for some reason a while back. I'll find how it previously worked and see why I changed it

**Comment by KadenZipfel** [comment]
Here we can see the changes that caused this: https://github.com/protofire/omen-exchange/commit/81ae1cdcae0db790dd655dc65a841a480b0c4a2e

I think the issue here was that when I made changes to the routing, the route history would be pushed incorrectly. Given this complex routing, I'm not sure of an easy way to set `backTo` while maintaining our filter routes.
