### ISSUE TITLE
gas limit estimations are way off

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1033]
I am currently trying to redeem winnings for market:
https://omen.eth.link/#/0xe17a114ebe42ee2065fdc642398fc0e993142b4a

it looks like the gas limit estimations are way to high:
<img width="358" alt="Screenshot 2020-08-03 at 15 11 47" src="https://user-images.githubusercontent.com/5337809/89186356-f4af5580-d59b-11ea-9768-21be747bd569.png">

**Comment by zippoxer** [comment]
Can reproduce. Trying to buy shares in [this](https://omen.eth.link/#/0x0fd30f7e7532ae38d6c97008703b3780f804bddf/buy) market, I this scary estimation:

![image](https://user-images.githubusercontent.com/859015/89216450-14ae3b80-d5d3-11ea-8214-94a739b8b1c9.png)

**Comment by Ingalandia** [comment]
https://twitter.com/salamanderrock/status/1290820498612465664

**Comment by KadenZipfel** [comment]
Assuming this is an issue with the CPK, this issue is dependent on https://github.com/gnosis/contract-proxy-kit/issues/101

**Comment by cag** [comment]
That's the gas limit for the block, so I'm guessing something is going on with the binary search for the true tx gas limit...

**Comment by pimato** [comment]
I believe this was a metamask error which appeared not only on Omen but throughout the ecosystem. Will close until we are sure it is an Omen issue.

**Comment by cag** [comment]
Throttling support has been enabled in ethers.js since [5.0.6](https://github.com/ethers-io/ethers.js/releases/tag/v5.0.6). In order to upgrade to that, an upgrade to CPK 2.0.0 is necessary (contains ethers v5 support from https://github.com/gnosis/contract-proxy-kit/pull/91). There's a small bit of porting necessary to upgrade to the new CPK 2.x releases, as the interface has changed a bit (a new object has to be initialized, but it shouldn't be that big of a change).
