### ISSUE TITLE
Consistent number formatting

### ISSUE THREAD

**Issue by auryn-macmillan** [protofire/omen-exchange#1060]
I'd like to talk quickly about number formatting.
Can we agree on a suggested format for expressing thousands and decimals?
I've seen four different formats on Omen so far, and it would be great to settle on one to make a more consistent UX.

Here are some formats that I'm aware of.
```
A) 10,000.00
B) 10.000,00
C) 10 000.00
D) 10 000,00
E) 10000.00
F) 10000,00
```

Currently, the UI formats like E), but this can be very difficult to read for larger numbers.
I've seen markets that use A), B), C), and E).

My personal preference is for A), since it is what most native English speaking countries use and the UI is in English.

Once we settle on a format, we should enforce it on the UI and suggest it for market creators.

At some point in future, we may even decide to make markets that use a different number format to be invalid.

**Comment by auryn-macmillan** [comment]
Another part of this that needs to be considered is how to express numbers with lots of decimal places (this is somewhat unique to interfaces dealing with crypocurrencies).

I would suggest that we display 2 decimal places whenever we express more than 1 of a token.
e.g. `1.23`
If we are expressing less than 1 of token, then we should show one place beyond the most significant digit.
e.g. `0.12` or `0.0012`

**Comment by KadenZipfel** [comment]
I definitely agree we should be consistent with formatting. That being said, I know it varies based on location, so I wonder if there exists a library that will parse each number into the correct format per location. Otherwise I agree that A) will probably be best understood overall.

> I would suggest that we display 2 decimal places whenever we express more than 1 of a token.
e.g. 1.23
If we are expressing less than 1 of token, then we should show one place beyond the most significant digit.
e.g. 0.12 or 0.0012

This seems like a good approach to me. I would just add that if someone is inputting their entire balance, it should display all digits.

**Comment by KadenZipfel** [comment]
@pimato What do you think?

**Comment by auryn-macmillan** [comment]
@KadenZipfel I'm sure there is a library that could format numbers appropriately for countries, but it might be tricky to do it for the question strings. So in the interest of being consistent throughout the UI and in the question guidelines, I'd suggest picking a format.
