### ISSUE TITLE
Reality.eth link fails if metamask enabled but not connected

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1081]
Currently, to decide whether to use reality.eth or reality.eth.link, we are checking whether metamask is enabled. This approach is flawed, and we should instead be checking if the user has their wallet connected.

**Comment by pimato** [comment]
not all wallets are ENS compatible which could lead to issues with correctly resolving the contentHASH of an ens domain.

**Comment by Mi-Lan** [comment]
maybe i can jump on this issue since i'm familiar with metamask and have already implemented check for the exact thing? 
-suggestion on how to implement this...so if user is connected his address is exposed and can be seen with following method "ethereum.selectedAddress", if it returns null then there is no user connected if it returns address then there is user connected. 
We can also listen to event metamask provides that is called every time user changes address or disconnects his wallet (https://docs.metamask.io/guide/ethereum-provider.html#accountschanged)
@KadenZipfel @pimato

**Comment by KadenZipfel** [comment]
> -suggestion on how to implement this...so if user is connected his address is exposed and can be seen with following method "ethereum.selectedAddress", if it returns null then there is no user connected if it returns address then there is user connected.

Does this work with Metamask's recent update to default users to not be connected? Sounds like it should

**Comment by Mi-Lan** [comment]
> > -suggestion on how to implement this...so if user is connected his address is exposed and can be seen with following method "ethereum.selectedAddress", if it returns null then there is no user connected if it returns address then there is user connected.
> 
> Does this work with Metamask's recent update to default users to not be connected? Sounds like it should, if so I'd say go for it.

well i tested it before i posted this comment and seems to work, they would mention something like that in docs like they do for depreciated stuff
