### ISSUE TITLE
List item component inefficiently loads data for all filters

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1121]
Instead of loading data for all filters at once, we should only load for the selected filter.

**Comment by Mi-Lan** [comment]
Upon consideration we came to conclusion that this tasks is redundant:
Explanation:
So the goal was to optimize filters and instead of fetching all data for filters at once we would fetch it based on what filter is selected. But as we figured out, data that was fetched in component is not fetched directly from subgraph but was extracting data from subgraph call that contains data for all filters. Hence optimisation would have to be done on the subgraph side and that is task  is much bigger than scope of this issue.
