### ISSUE TITLE
Disable creation of market with same question and currency as existing market

### ISSUE THREAD

**Issue by KadenZipfel** [protofire/omen-exchange#1280]
We want to be able to multiple markets with the same question, but only if they're based in different currencies. Creating a duplicate market like this would at best result in a user wasting gas, but likely also cause some ugly effects to the interface.

**Comment by pimato** [comment]
I´ve been working on a message for this:
<img width="714" alt="create-market" src="https://user-images.githubusercontent.com/5337809/98078496-77cd9980-1e72-11eb-94c7-f931cbdf7ce4.png">

this message:
<img width="824" alt="Bildschirmfoto 2020-11-04 um 07 52 35" src="https://user-images.githubusercontent.com/5337809/98078632-b82d1780-1e72-11eb-922d-2747ec9f09d3.png">

... should appear as a replacement for the default message if a market with the picked currency already exists:
<img width="823" alt="Bildschirmfoto 2020-11-04 um 07 51 37" src="https://user-images.githubusercontent.com/5337809/98078559-97fd5880-1e72-11eb-85c8-58d2e2a690eb.png">

**Comment by Mi-Lan** [comment]
@KadenZipfel @pimato i think we need to put more thought into this...because i'm not sure if there is a good way to figure out if there is same question on our platform...if i compare strings of market being created and questions on reality even if there are same questions they is high probability that questions are just written differently...maybe as user is typing question we can query reality questions and display questions with similar text in them so he sees if there is already market for them before he creates it...

**Comment by pimato** [comment]
@Mi-Lan lets focus only on imported markets for now which will reuse a questionId from reality.eth. So if a user wants import a market with an already existing currency, we should disable the creation of it.

**Comment by Mi-Lan** [comment]
> @Mi-Lan lets focus only on imported markets for now which will reuse a questionId from reality.eth. So if a user wants import a market with an already existing currency, we should disable the creation of it.

ok!
