### ISSUE TITLE
Reality link not working while on xDai relayer

### ISSUE THREAD

**Issue by Mi-Lan** [protofire/omen-exchange#1745]
Steps to reproduce:
1)Make sure to be on branch where relayer pr is merged
2)Switch to xDai on the relayer button
3)Go to any market
4)Click on the reality.eth on additional market data 
5)Leads nowhere!

https://user-images.githubusercontent.com/33226956/111623052-2eab3000-87ea-11eb-8f0b-77d158a5ad6f.mov

Also for scalar markets on answer reality question as well! Heres where it can be seen http://localhost:3000/#/0x071bc23726c6363e2c017185ff431c4d2d9ddf8d

![Screenshot 2021-03-18 at 13 08 22](https://user-images.githubusercontent.com/33226956/111623737-0f60d280-87eb-11eb-9ec6-d9293308a90e.png)

**Comment by KadenZipfel** [comment]
So the problem here is that we can incorporate a check if the relay is being used in `useRealityLink`, which will send it to the xDai reality URL, but we can't actually view the reality item unless we switch our network to xDai. I've incorporated this partial fix here: https://github.com/protofire/omen-exchange/pull/1758
