### ISSUE TITLE
Can't interact with markets using Gnosis Safe

### ISSUE THREAD

**Issue by dasanra** [protofire/omen-exchange#1882]
After few months I was trying to redeem tokens from a market. I was using a Gnosis Safe. I had issues not seeing any pending to redeem tokens when I was pretty sure I had a winning outcome.

The Gnosis Safe is using a Proxy contract to interact with Omen. I saw that the outcome tokens were still assigned to that Proxy when directly interacting with Conditional Tokens smart contract.

After investigating a bit I decided to run the interface locally, I wasn't able to see any other markets in which I participated under "MY_MARKETS" filter. I had to rollback until v1.2.2 until I was able to see the markets I participated and correctly seeing my outcome tokens in the market I had pending to redeem.

Steps to reproduce:
1.- Pick an Omen market using v1.2.2 of the interface
2.- Connect a Gnosis Safe wallet via WalletConnect
3.- Interact with the desired market
4.- Run any Omen interface version >=v1.2.3
5.- You won't see your outcome tokens or be able to list the markets where you have participated

User CPK:
0xb6f59e8A57295125680f01c398fd4019100b1Ce1

**Comment by hexyls** [comment]
Thanks for the heads up @dasanra  👍

This behaviour is annoying but expected and you experienced this because you are awesome and used Omen much earlier than other people.

As you explained in your post your Gnosis Safe was using an additional proxy contract to interact with Omen. That additional proxy contract was unnecessary so in newer versions of Omen we use your Gnosis Safe directly so that you are not wasting any gas.
