### ISSUE TITLE
Omen market details view crashed after redeemed winnings

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1903]
<img width="1058" alt="Bildschirmfoto 2021-05-10 um 17 40 04" src="https://user-images.githubusercontent.com/5337809/117686169-e3dce180-b1b6-11eb-9e81-33a2e43420f2.png">

**Comment by KadenZipfel** [comment]
This is really odd... I haven't managed to reproduce, but looking at the stack trace, it seems to be only when the `history_select` component is active. I'm guessing the issue is at `const R = r.div(1 - fee)` in `calcSellAmountInCollateral` where fee is somehow `1` (100% fee), which is super odd since it shouldn't be possible and the fee is directly grabbed from the subgraph. It would be good to know which market this happened on to see if there's any good reason.

I would say this can probably be ignored as long as it doesn't reappear since in production the user wouldn't see this error message and would simply not have a correct value for the amount of shares for some history item

**Comment by pimato** [comment]
closing for now!
