### ISSUE TITLE
claiming tokens immediately after successful withdraw fails

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1942]
A user needs to claim their withdrawn tokens after the withdraw transaction has been confirmed. It looks like the UI is missing some data as claiming does not work immediately after the withdraw transaction was successful. The console gives me an error:
<img width="802" alt="Bildschirmfoto 2021-05-27 um 12 52 58" src="https://user-images.githubusercontent.com/5337809/119814257-7cc76880-beea-11eb-9335-872d2a918f37.png">

here is a scenario:
![Bildschirmaufnahme 2021-05-27 um 11 58 14](https://user-images.githubusercontent.com/5337809/119814345-94065600-beea-11eb-9938-524004e755e2.gif)

**Comment by Mi-Lan** [comment]
@hexyls So I tried my best to solve this today seems that issue is that when fetching latest transactions there are not signatures present and it throws error that geronimo outlined
![Screenshot 2021-05-27 at 16 12 02](https://user-images.githubusercontent.com/33226956/119902966-3ef92d00-bf48-11eb-9a29-fb6cdd99115e.png)
Being inspired by your elegant solution with waitForBridgeMessageStatus i began digging into bridge contracts and found that they set required confirmations to 12
![Screenshot 2021-05-28 at 00 05 27](https://user-images.githubusercontent.com/33226956/119903051-6bad4480-bf48-11eb-9623-494826779982.png)
Heres link to smart contract....I tried many things something similar to what you have done also fetching data in while loop until signatures become present but those solutions didn't seem to fit the bill. So i just set the required block confirmations to 13 so we are guranteed to catch graph data with signatures present. What do you think?
