### ISSUE TITLE
Omen crashes on history loading of xDai market

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#1977]
Connection: xDai Tight, direct xDai connection
Market: http://localhost:3000/#/0xccef28ccbd16320aa614bbf594936d9dfc8d8a09

Steps to reproduce: 
1) Got to http://localhost:3000/#/0xccef28ccbd16320aa614bbf594936d9dfc8d8a09
2) Click History
3) BUG, frontend crashes

https://user-images.githubusercontent.com/5337809/121694121-18033500-caca-11eb-9808-6b00fc956bb5.mov

<img width="1086" alt="Bildschirmfoto 2021-06-11 um 15 29 55" src="https://user-images.githubusercontent.com/5337809/121694125-19346200-caca-11eb-97dd-5a54302a3f08.png">

**Comment by Mi-Lan** [comment]
This is related to pr #1952

**Comment by KadenZipfel** [comment]
I actually think this is a more general error. Seems to be failing if `firstItem` is zero, and this is happening because their is no liquidity. So it's likely a problem for all no liquidity markets.

I think also that using `calcSellAmountInCollateral` with a changing `balances` array will lead to an inconsistent value so should probably be done differently.
