### ISSUE TITLE
Check if build can be replicated with the same IPFS hash

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#643]
Check if `yarn build` or `npx react-scripts build` in combination with `ipfs add -r /build` will result in one unique IPFS Hash which can be generated by any user.

**Comment by hpmaxi** [comment]
It isn't possible to have a unique IPFS hash between different computers. Take into consideration to always use `yarn build` or `npm run build` to use the build script of `package.json`, this one is different from the default script that run with `npx react-scripts build`

**Comment by leolower** [comment]
From @pimato 
```
this can generate different IPFS hashes:
- Using different environment variables, even having it enabled and empty, I see you have LOT of them in the .env.example
- Having file hashes enabled in webpack.config.
For example:
      filename: isEnvProduction
        ? 'static/js/[name].[contenthash:8].js'
        : isEnvDevelopment && 'static/js/bundle.js',
 in react-scripts/config
You see it is adding the contentHash to the files, this will generate different names for each file in each machine.

Also, we might want to disable the devtool and source-maps, we dont use it in our webcpack.config.

So yeah, if you use the same ENV variables in two different machines and have the webpack.config configured correctly you should be able to reproduce the same hash.
I would reccomend having your own webpack config, this the one we use in BC-Dapp: https://github.com/levelkdev/BC-DAPP/blob/master/config/webpack.config.js
```

**Comment by fvictorio** [comment]
Modifying the `webpack.config.js` means doing a [`yarn eject`](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) before. We can do that, of course, but after that all the webpack maintenance must be done inside the project (instead of just updating `react-scripts`).

The alternative I propose is to build the assets inside docker. This minimal Dockerfile should do the trick:

```dockerfile
FROM node:12.16.0

WORKDIR /app

RUN git clone https://github.com/protofire/gnosis-conditional-exchange.git

WORKDIR /app/gnosis-conditional-exchange/app

RUN yarn

RUN cp .env.example .env
RUN yarn build

CMD true
```

Then any user should be able to build the docker image and then run the `ipfs add` command within it.

I made this file as a standalone dockerfile for simplicity, but ideally this would be a file inside the project that `ADD`s the files instead of cloning the project. Also an extra step is needed for configuring the `.env` file.

Again, any option is probably fine. I am generally against ejecting the project if it's not needed, but it's just a personal preference.
