### ISSUE TITLE
Answer Probability Values Error in Edge Cases

### ISSUE THREAD

**Issue by remedcu** [protofire/omen-exchange#714]
Error Page Link: https://conditional.netlify.app/#/create

Check the Answer Probability Values.

![Imgur](https://imgur.com/7q67P2x.png)

To replicate this error:

1. Add any Value greater than 99.01 to 99.99 with two decimal numbers (.X1 to .X9, where X should not be 0) to "Answer 1"'s probability %
2. Add another answer, say "Answer 2" and press "set max" which gives these values.

**Comment by fvictorio** [comment]
This is a presentation issue. We should round the numbers shown, not only for this case (this is a IEEE 754 "issue") but for example for the three outcomes with uniform probabilities case, where `33.333333333333336%` is shown.

This is a liiiittle harder to fix than what it seems, although not very hard. I mean, it's not just adding a `toFixed(2)` for the values, since we also check that they add to 100 (maybe we could just not check that if the uniform option is set?). We also should check that rounding doesn't mess up with the distribution hint calculation, but I don't think so.

**Comment by remedcu** [comment]
A simple solution (but a bitter UX and in a small way, unfair) would be to limit to 2-3 decimal places as you recommended, and when the no. of options added leads to a non zero remainder (like 100/3, giving 33.33%, leaving 0.01%) to show a warning that one of the options will have 0.01% higher or so, and to edit it or so.

Con:
Bitter UX - User has to make the change
Unfair - Not starting from a level ground for all the possibilities

Pros:
- Solves our problem of constituting 100%

**Comment by fvictorio** [comment]
Yeah, I don't think most users will care about the odds not being "exactly" uniform. Plus, there are probable better solutions. For example, we could show a different component for the probabilities (instead of disabled `<input type="number" />`s) where it's easier to show a prettier value, while the "real" value is more precise.

Plus, the odds don't even matter that much, the important part is the distribution hint that is computed later. If the "uniform" flag is carried on as part of the creation data (which is not done right now), then it's just a matter of using `[]` as distribution hint when the market is created.

**Comment by KadenZipfel** [comment]
Closing since this appears to be resolved.
