### ISSUE TITLE
Trade History does not reflect the current state 

### ISSUE THREAD

**Issue by pimato** [protofire/omen-exchange#829]
<img width="621" alt="Screenshot 2020-06-20 at 20 55 57" src="https://user-images.githubusercontent.com/5337809/85209470-9b1b0080-b338-11ea-8136-2e90e0df30d4.png">

**Comment by KadenZipfel** [comment]
So I did some digging on this, and it looks like the most recent block in which data is gathered from is set to be the start of the current date. This seems like it's not something we want, since every trade that happened on the current date will not be reflected by the chart, which is quite misleading. There must be some reason it's been implemented though since a function is explicitly created for this purpose. For reference, the function in question is `calcOffsetByDate()` in `app\src\components\market\common\history_chart\index.tsx`.

**Comment by hpmaxi** [comment]
Yes, @KadenZipfel is right, the idea behind `calcOffsetByDate` is to only retrieve blocks before the closing date because, after it, the state should be always the same and the chart will not reflect the relevant data previous to closing the market.

But also `calcOffsetByDate` take into account the current time to give you data for open markets taking as block reference the one starting at 00:00 to have data points from the same hour each day and avoid the problem of seeing a chart with data that changes if you enter to see the chart at different hours. To change this behavior, you can change how `blockOffset` is calculated to not use `calcOffsetByDate()`  if the market is open.

This should work.

```javascript
const blocksOffset = useMemo(
    () => (answerFinalizedTimestamp ? calcOffsetByDate(answerFinalizedTimestamp.toNumber()) : 0),
    [answerFinalizedTimestamp],
  )
```
